version: "3.6"

volumes:
  test-mysql:

services:
  mysql:
    build:
      dockerfile: ./mysql/Dockerfile
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - test-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
    container_name: nginx_web
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build:
      dockerfile: ./php/Dockerfile
    container_name: php8.1
    volumes:
      - ./:/var/www/html
